# name: Deploy Dist
# on: [push,workflow_dispatch]      # it will trigger the workflow on push event and also can be triggered manually
# # on:                               #both are same(used for array of object)
# #     -push
# #     -workflow_dispatch
# jobs:
#     test:
#         runs-on: ubuntu-latest
#         steps:
#             -name: Get Code
#             #   run: 
#             #     echo "cloning repo..."
#             #     echo "${{toJson(github)}}"
#             #     git clone https://github.com/${{github.repository}}.git


# # to see the github context details
# # cloning the current repository using github context    
# # https://github.com/Ritik8483/ci_cd_repository_react.git



# --------------SIMPLE VERSION -----------------


name: Deploy Dist
# on: [push,workflow_dispatch]
on:                         #for ading filter
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - '.github/workflows/*'               #ignoring changes in these files and doesn't trigger pipeline
  workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code"
              uses: actions/checkout@v6
            - name: Install Node 20
              uses: actions/setup-node@v4
              with: 
                node-version: 20
            - name: print node version
              run: node -v

            - name: Cache Dependencies
              uses: actions/cache@v4
              with: 
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              run: npm ci 
            - name: Run Tests
              run: npm run test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code"
              uses: actions/checkout@v6

            - name: Install Node 20
              uses: actions/setup-node@v4
              with: 
                node-version: 20
                  
            - name: Cache Dependencies
              uses: actions/cache@v4
              with: 
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              run: npm ci 

            - name: Build Project
              run: npm run build

            - name: Upload Dist Folder                  # uploading dist folder as artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist-folder               #name must be same while downloading
                path: dist/                   #path of the folder to be uploaded

    deploy:
        needs: build                 #this will run after sucessful completion of test job
        runs-on: ubuntu-latest
        steps:
            - name: Download Dist Folder                  #uploading dist folder as artifact
              uses: actions/download-artifact@v4
              with:
                name: dist-folder 
                path: dist/
            - name: Deploy
              run: echo "Deploying the project..."          #for now we use echo only


    # deploy:
    #     needs: build                 #this will run after sucessful completion of test job
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: "Get Code"
    #           uses: actions/checkout@v6

    #         - name: Install Node 20
    #           uses: actions/setup-node@v4
    #           with: 
    #             node-version: 20
                  
    #         - name: Cache Dependencies
    #           uses: actions/cache@v4
    #           with: 
    #             path: ~/.npm
    #             key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    #         - name: Install Dependencies
    #           run: npm ci 

    #         - name: Build Project
    #           run: npm run build

    #         - name: Deploy
    #           run: echo "Deploying the project..."


#bydefault it runs both jobs in parallel we make them run sequentially using depends-on
# search cache inside github market place for caching dependencies step
# filter is used to specify specific branch for pipeline to trigger

#Upload and download artifacts(.dist folder i.e, asset generated) using actions/upload-artifact and actions/download-artifact
# we use build so doen't need access code inside deploy

#DEPLOYMENT search actions/deploy-pages and create a seperate workflow
# Settings -> Pages 
# Token Settings -> Secrets - >
# Add repository name in vite config inside base and also add it in package.json file
# base:'/ci_cd_repository_react/',  // add repository name in vite config
